#!/bin/bash

echo "🚀 PhishingSense Database Setup & Diagnostics"
echo "============================================="

# Check environment configuration
echo "📄 Checking environment configuration..."
if [ -f ".env.local" ]; then
    echo "✅ .env.local found"
    echo "📋 Supabase configuration:"
    grep -E "SUPABASE" .env.local || echo "❌ No Supabase variables found"
else
    echo "❌ .env.local not found!"
    echo "📝 Please create .env.local with:"
    echo "NEXT_PUBLIC_SUPABASE_URL=https://saxmpvvgjkidotpqsaht.supabase.co"
    echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNheG1wdnZnamtpZG90cHFzYWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNjQ2NTAsImV4cCI6MjA3Njk0MDY1MH0.Z05qOMiT_OnNLD3WwNxd-gTEwg1LRSwHDoYQOpq7vEY"
    exit 1
fi

echo ""
echo "🗄️  DATABASE SETUP INSTRUCTIONS:"
echo "================================="
echo "1. 🌐 Go to your Supabase project:"
echo "   https://supabase.com/dashboard/project/saxmpvvgjkidotpqsaht"
echo ""
echo "2. 📝 Navigate to SQL Editor"
echo ""
echo "3. 📋 Copy and paste the ENTIRE contents of supabase-schema.sql"
echo "   (File is in your project root directory)"
echo ""
echo "4. ▶️  Click 'Run' to execute the schema"
echo ""
echo "📋 What the schema creates:"
echo "• users, scan_logs, reports, user_settings, patterns, comments tables"
echo "• Row Level Security (RLS) policies for all tables"
echo "• 150+ phishing detection patterns"
echo "• Analytics functions and triggers"
echo "• Proper indexes for performance"
echo ""
echo " If you get 'relation already exists' errors:"
echo "• The schema has been partially applied before"
echo "• Try running the schema again (it uses CREATE TABLE IF NOT EXISTS)"
echo "• Or use ./reset-database.sh to start completely fresh"
echo ""
echo " ERROR CODE REFERENCE:"
echo "• 42P01 = Tables don't exist (schema not run)"
echo "• 42501 = Access denied (RLS policy issue)"
echo "• 23505 = Duplicate entry (already exists)"
echo "• 42P07 = Table already exists (schema partially applied)"
echo ""
echo " AFTER SETUP:"
echo "1. Restart your development server: pnpm dev"
echo "2. Try signing up with a test email"
echo "3. Check browser console for detailed error logs"
echo ""
echo " Alternative Setup Methods:"
echo "• Use Supabase CLI: supabase db push"
echo "• Manual verification: Check if tables exist in Supabase Dashboard"
echo ""
echo " Quick Fix for 'Already Exists' Errors:"
echo "Run this SQL first to drop existing tables:"
echo "DROP TABLE IF EXISTS public.users CASCADE;"
echo "DROP TABLE IF EXISTS public.scan_logs CASCADE;"
echo "DROP TABLE IF EXISTS public.reports CASCADE;"
echo "DROP TABLE IF EXISTS public.user_settings CASCADE;"
echo "DROP TABLE IF EXISTS public.patterns CASCADE;"
echo "DROP TABLE IF EXISTS public.comments CASCADE;"
echo ""
echo " After applying schema, visit http://localhost:3000"
echo "You should see the authentication interface working perfectly!"
